title: Jordan Nagadzina-Sanchez   Consultant Data
description: Welcome to my personal page! You'll find my posts and projects.

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 3 #3 articles affichés par page.

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Projects
      url: /projects
    - title: Posts
      url: /posts
    - title: Contact
      url: /contact

social:
    github: JordanNSZ
    #twitter: brianmaierjr
    #facebook: brianmaierjr
    email: jordan.nagadzina.sanchez@gmail.com
    linkedin: Jordan Nagadzina-Sanchez
    #youtube: RickAstleyYT
    #tumblr: i-am-a-fish

#google_analytics: "UA-58263416-1"

disqus:
    shortname: Jordan Nagadzina-Sanchez
